import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderColor: '#E2E8F0', paddingTop: Platform.OS === 'android' ? 40 : 20 },
  headerLeft: { flexDirection: 'row', alignItems: 'center' },
  menuButton: { marginRight: 15 },
  headerTitle: { fontSize: 22, fontWeight: 'bold', color: '#1E293B' },
  headerSubtitle: { fontSize: 14, color: '#64748B' },
  
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  simulateOrderBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#3B82F6', paddingHorizontal: 12, paddingVertical: 10, borderRadius: 8 },
  simulateOrderBtnText: { color: '#FFFFFF', fontWeight: 'bold', marginLeft: 6, fontSize: 14 },
  closeRegisterBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1E293B', paddingHorizontal: 12, paddingVertical: 10, borderRadius: 8 },
  closeRegisterBtnText: { color: '#FFFFFF', fontWeight: 'bold', marginLeft: 6, fontSize: 14 },

  tabContainer: { flexDirection: 'row', backgroundColor: '#FFFFFF', paddingHorizontal: 10, borderBottomWidth: 1, borderColor: '#E2E8F0' },
  tabButton: { flex: 1, paddingVertical: 15, alignItems: 'center', borderBottomWidth: 3, borderBottomColor: 'transparent' },
  tabButtonActive: { borderBottomColor: '#EA1D2C' },
  tabText: { fontSize: 13, color: '#64748B', fontWeight: '600' },
  tabTextActive: { color: '#EA1D2C', fontWeight: 'bold' },

  content: { flex: 1 },
  listPadding: { padding: 20 },
  emptyText: { textAlign: 'center', color: '#94A3B8', marginTop: 40, fontSize: 16 },

  card: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 16, marginBottom: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2, borderLeftWidth: 5 },
  cardMesa: { borderLeftColor: '#F59E0B' },
  cardLlevar: { borderLeftColor: '#10B981' },
  cardTransfer: { borderLeftColor: '#3B82F6', backgroundColor: '#EFF6FF' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  orderId: { fontSize: 14, color: '#94A3B8', fontWeight: 'bold' },
  orderTotal: { fontSize: 20, fontWeight: 'bold', color: '#1E293B' },
  orderTitle: { fontSize: 18, fontWeight: '700', color: '#334155', marginBottom: 4 },
  orderItemsPreview: { fontSize: 14, color: '#64748B', marginBottom: 16 },
  payButton: { backgroundColor: '#EA1D2C', borderRadius: 8, paddingVertical: 12, alignItems: 'center' },
  payButtonReview: { backgroundColor: '#3B82F6' },
  payButtonText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 16 },

  employeeCard: { backgroundColor: '#FFFFFF', padding: 16, borderRadius: 12, marginBottom: 16, elevation: 2, shadowColor: '#000000', shadowOpacity: 0.05, shadowRadius: 4, shadowOffset: { width: 0, height: 2 } },
  employeeHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  employeeInfoBox: { flexDirection: 'row', alignItems: 'center' },
  employeeAvatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#EFF6FF', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  employeeInitials: { color: '#3B82F6', fontWeight: 'bold', fontSize: 16 },
  employeeName: { fontSize: 18, fontWeight: 'bold', color: '#1E293B' },
  employeeRole: { fontSize: 14, color: '#64748B', marginTop: 2 },
  statusDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#10B981', marginTop: 6 },
  employeeDetailsBox: { backgroundColor: '#F8FAFC', borderRadius: 8, padding: 12, marginBottom: 14, gap: 8 },
  timeBox: { flexDirection: 'row', justifyContent: 'space-between' },
  timeLabel: { color: '#64748B', fontSize: 14, fontWeight: '500' },
  timeValue: { color: '#334155', fontSize: 14, fontWeight: 'bold' },
  payValue: { color: '#10B981', fontSize: 14, fontWeight: 'bold' },
  payShiftButton: { backgroundColor: '#3B82F6', borderRadius: 8, paddingVertical: 12, alignItems: 'center' },
  payShiftButtonText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 15 },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  modalBox: { backgroundColor: '#FFFFFF', width: '100%', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, paddingBottom: Platform.OS === 'ios' ? 40 : 24, elevation: 10 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { fontSize: 22, fontWeight: 'bold', color: '#1E293B' },
  closeIcon: { fontSize: 24, color: '#94A3B8', fontWeight: 'bold', padding: 5 },
  
  modalAcceptBtn: { width: '100%', paddingVertical: 16, borderRadius: 12, backgroundColor: '#EA1D2C', alignItems: 'center', marginTop: 15 },
  modalAcceptBtnDisabled: { backgroundColor: '#FDA4AF' },
  modalAcceptText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 16 },

  validationButtonsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 15, gap: 10 },
  btnReject: { flex: 1, paddingVertical: 16, borderRadius: 12, backgroundColor: '#EF4444', alignItems: 'center' },
  btnApprove: { flex: 1, paddingVertical: 16, borderRadius: 12, backgroundColor: '#10B981', alignItems: 'center' },
  
  proofContainer: { alignItems: 'center' },
  proofImage: { width: '100%', height: 150, marginVertical: 15, backgroundColor: '#F1F5F9', borderRadius: 8 },

  ticketContainer: { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 16, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 5 },
  ticketRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  ticketLabel: { fontSize: 15, color: '#64748B', fontWeight: '500' },
  ticketValue: { fontSize: 15, color: '#1E293B', fontWeight: 'bold' },
  ticketValueLarge: { fontSize: 18, color: '#EA1D2C', fontWeight: '900' },
  divider: { height: 1, backgroundColor: '#E2E8F0', marginVertical: 12 },
  ticketItemsHeader: { fontSize: 14, color: '#64748B', fontWeight: 'bold', marginBottom: 8, textTransform: 'uppercase' },
  itemsScroll: { maxHeight: 100 },
  ticketItemsList: { fontSize: 15, color: '#334155', lineHeight: 24 },

  addMissingBtn: { marginTop: 10, paddingVertical: 12, backgroundColor: '#EFF6FF', borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: '#3B82F6', borderStyle: 'dashed', flexDirection: 'row', justifyContent: 'center' },
  addMissingBtnText: { color: '#3B82F6', fontWeight: 'bold', fontSize: 14 },

  paymentMethodTitle: { fontSize: 14, fontWeight: 'bold', color: '#64748B', marginTop: 15, marginBottom: 10, textTransform: 'uppercase' },
  paymentOptionsRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  paymentMethodBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderWidth: 2, borderColor: '#E2E8F0', borderRadius: 10, backgroundColor: '#FFFFFF' },
  paymentMethodBtnActive: { borderColor: '#E61C24', backgroundColor: '#FEF2F2' },
  paymentMethodText: { fontSize: 14, fontWeight: 'bold', color: '#64748B', marginLeft: 6 },
  paymentMethodTextActive: { color: '#E61C24' },
  warningBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FEF3C7', padding: 10, borderRadius: 8, marginTop: 15, borderWidth: 1, borderColor: '#FDE68A' },
  warningText: { fontSize: 12, color: '#92400E', flex: 1 },

  catalogOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', padding: 20 },
  catalogBox: { backgroundColor: '#FFFFFF', borderRadius: 20, padding: 20, maxHeight: '80%', elevation: 15 },
  catalogHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  catalogTitle: { fontSize: 20, fontWeight: 'bold', color: '#1E293B' },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F1F5F9', borderRadius: 10, paddingHorizontal: 12, height: 45, marginBottom: 15 },
  searchInput: { flex: 1, marginLeft: 8, fontSize: 16, color: '#000', borderWidth: 0, borderColor: 'transparent' },
  catalogItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  catalogItemName: { fontSize: 16, fontWeight: '600', color: '#1E293B', marginBottom: 4 },
  catalogItemPrice: { fontSize: 14, color: '#10B981', fontWeight: 'bold' },
  catalogAddBtn: { backgroundColor: '#FEF2F2', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 8 },
  catalogAddBtnText: { color: '#EA1D2C', fontWeight: 'bold', fontSize: 13 },
  emptyCatalogText: { textAlign: 'center', color: '#94A3B8', marginTop: 30, fontSize: 15, fontStyle: 'italic' },

  // 🔥 ESTAS 3 CLASES SE HABÍAN BORRADO, LAS VOLVÍ A AGREGAR AQUÍ:
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 },
  totalLabel: { fontSize: 16, color: '#1E293B', fontWeight: 'bold' },
  totalValue: { fontSize: 24, color: '#EA1D2C', fontWeight: '900' },

  employeePaymentContainer: { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 20, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 20, alignItems: 'center' },
  empModalName: { fontSize: 22, fontWeight: 'bold', color: '#1E293B', marginBottom: 4 },
  empModalRole: { fontSize: 16, color: '#64748B', marginBottom: 16 },
  empModalDetails: { backgroundColor: '#FFFFFF', width: '100%', padding: 12, borderRadius: 8, flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20, borderWidth: 1, borderColor: '#E2E8F0' },
  empModalLabel: { color: '#64748B', fontSize: 14 },
  empModalValue: { color: '#1E293B', fontWeight: 'bold', fontSize: 14 },
  inputContainer: { width: '100%' },
  inputLabel: { fontSize: 14, color: '#334155', marginBottom: 8, fontWeight: '500' },
  currencyInputWrapper: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderWidth: 2, borderColor: '#3B82F6', borderRadius: 10, paddingHorizontal: 15, overflow: 'hidden' },
  currencySymbol: { fontSize: 24, color: '#1E293B', fontWeight: 'bold', marginRight: 5 },
  moneyInput: { flex: 1, minWidth: 0, fontSize: 28, fontWeight: '900', color: '#1E293B', paddingVertical: 12, borderWidth: 0, backgroundColor: 'transparent' },
  payEmployeeBtn: { width: '100%', paddingVertical: 16, borderRadius: 12, backgroundColor: '#3B82F6', alignItems: 'center' },

  summaryContainer: { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 20, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 24 },
  summarySubtitle: { fontSize: 14, fontWeight: 'bold', color: '#64748B', marginBottom: 16, textTransform: 'uppercase' },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  summaryItem: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  summaryLabel: { fontSize: 15, color: '#334155', marginLeft: 10, flexShrink: 1 },
  summaryValueEfectivo: { fontSize: 18, fontWeight: '900', color: '#10B981' },
  summaryValueTransfer: { fontSize: 18, fontWeight: '900', color: '#3B82F6' },
  totalSummaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  totalSummaryLabel: { fontSize: 18, fontWeight: 'bold', color: '#1E293B' },
  totalSummaryValue: { fontSize: 28, fontWeight: '900', color: '#E61C24' },
  closeShiftBtn: { width: '100%', paddingVertical: 16, borderRadius: 12, backgroundColor: '#1E293B', alignItems: 'center' },
  closeShiftBtnText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 16 },

  toastContainer: { position: 'absolute', top: Platform.OS === 'ios' ? 50 : 20, left: 20, right: 20, backgroundColor: '#10B981', padding: 16, borderRadius: 10, zIndex: 999, elevation: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 5 },
  toastText: { color: '#FFFFFF', fontWeight: 'bold', textAlign: 'center', fontSize: 15 }
});